//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12.09.2014 15:27:54
namespace EntityDeneme
{
    
    /// <summary>
    /// There are no comments for derslerEntities in the schema.
    /// </summary>
    public partial class derslerEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new derslerEntities object using the connection string found in the 'derslerEntities' section of the application configuration file.
        /// </summary>
        public derslerEntities() : 
                base("name=derslerEntities", "derslerEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new derslerEntities object.
        /// </summary>
        public derslerEntities(string connectionString) : 
                base(connectionString, "derslerEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new derslerEntities object.
        /// </summary>
        public derslerEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "derslerEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for kullanicilar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<kullanicilar> kullanicilar
        {
            get
            {
                if ((this._kullanicilar == null))
                {
                    this._kullanicilar = base.CreateQuery<kullanicilar>("[kullanicilar]");
                }
                return this._kullanicilar;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<kullanicilar> _kullanicilar;
        /// <summary>
        /// There are no comments for kullanicilar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTokullanicilar(kullanicilar kullanicilar)
        {
            base.AddObject("kullanicilar", kullanicilar);
        }
    }
    /// <summary>
    /// There are no comments for derslerModel.kullanicilar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// KullaniciID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="derslerModel", Name="kullanicilar")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class kullanicilar : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new kullanicilar object.
        /// </summary>
        /// <param name="kullaniciID">Initial value of KullaniciID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static kullanicilar Createkullanicilar(int kullaniciID)
        {
            kullanicilar kullanicilar = new kullanicilar();
            kullanicilar.KullaniciID = kullaniciID;
            return kullanicilar;
        }
        /// <summary>
        /// There are no comments for property KullaniciID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int KullaniciID
        {
            get
            {
                return this._KullaniciID;
            }
            set
            {
                this.OnKullaniciIDChanging(value);
                this.ReportPropertyChanging("KullaniciID");
                this._KullaniciID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("KullaniciID");
                this.OnKullaniciIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _KullaniciID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKullaniciIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKullaniciIDChanged();
        /// <summary>
        /// There are no comments for property Ad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Ad
        {
            get
            {
                return this._Ad;
            }
            set
            {
                this.OnAdChanging(value);
                this.ReportPropertyChanging("Ad");
                this._Ad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Ad");
                this.OnAdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Ad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAdChanged();
        /// <summary>
        /// There are no comments for property Soyad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Soyad
        {
            get
            {
                return this._Soyad;
            }
            set
            {
                this.OnSoyadChanging(value);
                this.ReportPropertyChanging("Soyad");
                this._Soyad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Soyad");
                this.OnSoyadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Soyad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSoyadChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSoyadChanged();
        /// <summary>
        /// There are no comments for property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Email;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmailChanged();
    }
}
